### ISSUE TITLE
gndn.py input not found cryptic error

### ISSUE THREAD

**Issue by eydrian** [uzh/gc3pie#500]
If the input path in gndn.py does not exist it prints out an error message ending with: 

```
TypeError: unsupported operand type(s) for &: 'str' and 'str'
```

A simple `file / path not found` would be nice

**Comment by riccardomurri** [comment]
I have just pushed a fix to the `master` and `develop` branches.  Could you please check if it works?

**Comment by eydrian** [comment]
Works! Thx
