### ISSUE TITLE
Feature request: error messages styling

### ISSUE THREAD

**Issue by eydrian** [uzh/gc3pie#501]
Feature request:
Would it be possible to highlight errors with e.g. colors?

I find it hard to spot the errors in the command window output. It would be nice to make errors more visible.

**Comment by riccardomurri** [comment]
All the ERROR output from GC3Pie programs is performed using Python's
`logging` library, which does not provide any colorization feature.

I have found this add-on library which is promising:
https://pypi.python.org/pypi/coloredlogs

Upon installation (`pip install coloredlogs`) it will also provide a
`coloredlogs` program that colorizes every log line with a different
tint.  You can try it out with::

       coloredlogs gndn #... everything else as normal

Is that what you're looking after?

**Comment by eydrian** [comment]
Okay I see. Unfortunately that doesn’t work. Using it from the command line (OSX 10.11) produces an an error: `script: illegal option -- e
usage: script [-adkpqr] [-t time] [file [command ...]]`

But wouldn't it be nice if this package could be included in the top level gc3utils.log. 
I tried to add it but didn't really get what file is actually triggering the log.

Anyway, shouldn't it be possible to hook the `coloredlogs` somewhere to the main logger?
--> logging.getLogger("gc3.gc3libs")

**Comment by riccardomurri** [comment]
Log colorization enabled in the "develop" branch; will be released in GC3Pie 2.5.

If you have any time to test code in "develop", I would appreciate any feedback.

**Comment by eydrian** [comment]
Works like a charm. Great! Does exactly what I wished for. Thanks
