### ISSUE TITLE
Remove examples for Hobbes cloud and add example for ScienceCloud in gc3pie.conf and RTD documentation

### ISSUE THREAD

**Issue by arcimboldo** [uzh/gc3pie#502]
In the gc3pie.conf example and in the documentation there are references to Hobbes but no reference to ScienceCloud.

The example gc3pie.conf should contain already a commented out section for ScienceCloud (using uzh-only network) and the documentation as well should have some information about how to configure gc3pie for ScienceCloud

**Comment by smaffiol** [comment]
Will also replace/update the references to GC3

**Comment by riccardomurri** [comment]
Fix available in the "develop" branch.
