### ISSUE TITLE
gc3pie.conf file missing network_ids option

### ISSUE THREAD

**Issue by taleksiev** [uzh/gc3pie#510]
The current gc3pie.conf is missing completely the documentation about the network_ids option and will generate the following error when trying to run a work-flow:

"AttributeError: 'OpenStackLrms' object has no attribute 'network_ids'"

**Comment by arcimboldo** [comment]
That's probably the cause: https://github.com/uzh/gc3pie/blob/master/gc3libs/backends/openstack.py#L260 the code of `_create_instance` assumes there is an attribute `network_ids` but the constructor does not define it.

**Comment by riccardomurri** [comment]
Fixed in #644
