### ISSUE TITLE
Parsing LSF's `bjobs -l` output fails at times

### ISSUE THREAD

**Issue by riccardomurri** [uzh/gc3pie#513]
Issue reported by Jens Hooge on the mailing list: https://groups.google.com/forum/#!topic/gc3pie/LMFTUVgL5F8 (which see for details and further discussion).

**Comment by riccardomurri** [comment]
Still under investigation; initial guess is that `bjobs -l` can under some conditions produce empty output, and GC3Pie's `LsfLrms._parse_stat_output()` raises a `ValueError` exception.

**Comment by riccardomurri** [comment]
Code to get complete `bjobs -l` output in the logs is now available in branch "issue#513".

**Comment by jhooge** [comment]
Thanks for looking into this.
You should be able to reproduce this error by setting the variable `CLEAN_PERIOD` in `lsb.params` file to a small value (in seconds) and start a gc3pie script that runs longer than this value. This variable sets the time that finished job records are kept in mbatchd core memory, such that the `bjobs` command will still list jobs after they have finished. 

Per default `CLEAN_PERIOD` is set to one hour. If `bjobs` is called after this time has passed `bjobs -l` will not list finished jobs anymore. As far as I understand it gc3pie, calls `bjobs -l` in certain time intervals while a gc3pie script is running. if `bjobs -l` is called after `CLEAN_PERIOD` it will not return any stdout, such that `LsfLrms._parse_stat_output()` raises a `ValueError`.

**Comment by riccardomurri** [comment]
Hello @jhooge , thanks for digging into this and finding the root cause!

On the only LSF cluster to which I have access to ATM, the following
happens when I try to run `bjobs` on a job that has finished execution
since more than CLEAN_PERIOD:

      [rmurri@frt ~]$ bjobs -l 943186; echo $?
      Job <943186> is not found
      0

I.e., `bjobs` exits with code 0 but prints a message to STDERR.  Does
the same happen in your cluster?  Do you see this condition being
reported in the GC3Pie logs before the job turns to UNKNOWN state?

**Comment by jhooge** [comment]
Yes, in my logs I can see the same behaviour:
```
[2016-03-03 13:22:52] gc3.gc3libs  DEBUG   : About to update state of application: RestrEfficiencyApp.2000 (currently: UNKNOWN)
[2016-03-03 13:22:52] gc3.gc3libs  DEBUG   : Opening LocalTransport...
[2016-03-03 13:22:52] gc3.gc3libs  DEBUG   : Checking remote job status with 'bjobs -l 26219' ...
[2016-03-03 13:22:52] gc3.gc3libs  DEBUG   : Executed local command 'bjobs -l 26219', got exit status: 0
[2016-03-03 13:22:52] gc3.gc3libs  DEBUG   : Command `bjobs -l 26219` did not produce *any* STDOUT.
[2016-03-03 13:22:52] gc3.gc3libs  DEBUG   : Command `bjobs -l 26219` produced the following STDERR lines:
[2016-03-03 13:22:52] gc3.gc3libs  DEBUG   : ```Job <26219> is not found```
[2016-03-03 13:22:52] gc3.gc3libs  DEBUG   : ``````
[2016-03-03 13:22:52] gc3.gc3libs  WARNING : Unknown batch job status, setting GC3Pie job state to `UNKNOWN`
```

**Comment by riccardomurri** [comment]
I think this is fixed in the "develop" branch, commit b447fcc.  Can you please test it?

**Comment by jhooge** [comment]
I have no write access to lsb.params and will have to talk to one of our cluster admins before I can test it. Right now we've set `CLEAN_PERIOD` to 4 days and naturally I won't encounter this error unless I can change that value again. This has to wait until next week, though. I need to process some data first.

**Comment by riccardomurri** [comment]
Since there have been no updates, can I presume that the problem has been solved?

**Comment by riccardomurri** [comment]
Given no new data nor complains since about a year, I'm marking this as "solved".
