### ISSUE TITLE
OpenStack backend should not set attributes on the main `Application` object

### ISSUE THREAD

**Issue by riccardomurri** [uzh/gc3pie#535]
Currently the OpenStack backend is using the `os_instance_id`
attribute, set directly on the main application instance, to record
what VM a job might be running on.

There's two problems with that:
- execution-specific attributes should be set on the `app.execution`
  object (a `Run` instance) instead of the main `Application` class
  instance;
- internal-use attributes should start with an `_`-character to make
  it clear it's internal use and not public attributes that every
  client can read and/or set.

It's quite possible that we have the same issue in the EC2 backend; need to check the code.

**Comment by arcimboldo** [comment]
I agree with not setting the application attribute, but other backends (slurm, shellcmd) already set attributes in the execution object as "slurm_*" or "shellcmd_*", so your second point it's inconsistent with the current behavior.

BTW, the EC2 backend also sets "ec2_instance_id" in the Application object.

**Comment by riccardomurri** [comment]
Fixed in 3516d378392aad08795469862955394e681820ae and preceding commits
