### ISSUE TITLE
No possibility to kill tasks that are not attached to the engine

### ISSUE THREAD

**Issue by HackerMD** [uzh/gc3pie#545]
One can only kill tasks that are attached to an engine object. But one should also be able to kill a task that was loaded from a ``Store``.

Here is some non-working dummy code that illustrates the problem

```python
import gc3libs
from gc3libs.persistence.sql import make_sqlstore

task = gc3libs.Application()
store = gc3libs.make_sqlstore()
store.save(task)

engine = gc3libs.create_engine(store)
engine.add(task)
engine.progress()

loaded_task = store.load(task.persistent_id)
engine.kill(loaded_task)
```

This is the traceback of the error raised by the actual code:

```
Traceback (most recent call last):
  File "/Users/mdh/gc3pie/gc3libs/core.py", line 1420, in progress
    self._core.kill(task)
  File "/Users/mdh/gc3pie/gc3libs/core.py", line 697, in kill
    self.__kill_task(app, **extra_args)
  File "/Users/mdh/gc3pie/gc3libs/core.py", line 751, in __kill_task
    task.kill(**extra_args)
  File "/Users/mdh/gc3pie/gc3libs/workflow.py", line 344, in kill
    self.tasks[self._current_task].kill(**extra_args)
  File "/Users/mdh/gc3pie/gc3libs/workflow.py", line 344, in kill
    self.tasks[self._current_task].kill(**extra_args)
  File "/Users/mdh/gc3pie/gc3libs/workflow.py", line 344, in kill
    self.tasks[self._current_task].kill(**extra_args)
  File "/Users/mdh/gc3pie/gc3libs/workflow.py", line 813, in kill
    task.kill(**extra_args)
  File "/Users/mdh/gc3pie/gc3libs/__init__.py", line 403, in kill
    self)
AssertionError: Task.kill() called on detached task 42510.
```

There is also no method that would allow retrieving the attached task from the engine based on the ``persistent_id``.

**Comment by riccardomurri** [comment]
> One can only kill tasks that are attached to an engine object.

Yes, by design.

`Engine` and `Core` are the classes doing the actual job control; you cannot operate on a job without the intermediation of an Engine or a job.

If you need to operate on a `Task`, attacjh it to an Engine or Core first:

    task.aatach(engine)
    task.kill()

or equivalently::

    engine.add(task)
    engine.kill(task)

**Comment by HackerMD** [comment]
I see! But isn't it a problem when the same computational task is added to the engine twice?

**Comment by riccardomurri** [comment]
> But isn't it a problem when the same computational task is added to the engine twice?

No, `Engine.add` is idempotent.

But why are you adding it twice, in the first place?

**Comment by HackerMD** [comment]
Ok! Good!

I'm running the engine in the background in a separate thread and don't have the task available in memory, but rather need to retrieve it from a persistent store. The task is then added once upon submission and a second time when I would like to kill it.

**Comment by riccardomurri** [comment]
Good! Remember to add the *same* task object, though!  Retrieving twice from the store may result in two different (but =) task objects, which will not be detected as = by `Engine.add`

**Comment by HackerMD** [comment]
That's what I was talking about. So it actually is a problem!

I cannot add the *same* object, because I would have to hold it in memory across different threads. Where's the point of having a persistent store then?

I think this needs to be changed. In my opinion ``kill()`` should work with the ``persistent_id`` of the task (which defaults to the Python object id in case there is no persistent store).

The engine updates the store, so it could also retrieve a task from the store to kill it. In addition, keeping all ``tasks`` in memory all the time represents a bottleneck anyways. We have already discussed the implementation of lazy collections, where only tasks in state ``NEW`` will be added to the engine and released once they are ``TERMINATED`` or ``STOPPED``.

**Comment by riccardomurri** [comment]
> In my opinion kill() should work with the persistent_id of the task

It sounds reasonable that `kill()`, `free()` and a few other methods
can accept *either* a task object *or* a task ID.

I have opened issue #548 to track that idea -- this conversation was
about a different request and I'd like to keep the conversations close
to the subject topic.


> The engine updates the store, so it could also retrieve a task from
> the store to kill it. In addition, keeping all tasks in memory all
> the time represents a bottleneck anyways.

This is definitely the way to go in the long run (we already discussed
it), and I think I have drafted code somewhere named `XlEngine` to do
exactly that. But it is a relatively major effort so please do no
expect it to land on "master" soon.
