### ISSUE TITLE
Parse backend specific arguments to Task constructor

### ISSUE THREAD

**Issue by HackerMD** [uzh/gc3pie#547]
There are cases where one needs to provide additional submission arguments. For example, to implement fair job scheduling across multiple users and accounts with SLURM one may need to specify `--account` or `--user`.

Currently, this can not be done programatically in the API. One could use the `environment` argument to specify an environment variable and alias `sbatch` in the config file, but this is very hacky and has many problems associated with it. It would be way cleaner to pass these arguments to the `Task` constructor.

e.g.:

```python
app = Application(
    arguments=['hostname'],
    inputs=[],
    outputs=[],
    batch_arguments={'account': 'myAccount'}
)
```

The key, value pairs of the `batch_arguments` mapping could then be appended to the actual submission command (here illustrated for the SLURM backend in [slurm.py](https://github.com/uzh/gc3pie/blob/develop/gc3libs/backends/slurm.py#L193)):

```python
def _submit_command(self, app):
        sbatch_argv, app_argv = app.sbatch(self)
        if hasattr(app, 'batch_arguments'):
            valid_sbatch_args = {'account', 'user'}
            for name, value in app.batch_arguments.items():
                if name in valid_sbatch_args:
                    sbatch_argv.extend(['--{0}'.format(str(name)), str(value)])
        return (sh_quote_safe_cmdline(sbatch_argv),
                sh_quote_unsafe_cmdline(app_argv))
```

**Comment by HackerMD** [comment]
For this specific use case, it may also be worthwhile adding `user` and `account` attributes to the `Task` object, which will then be handled by the backend implementation. Job scheduling is probably relevant for many applications. The corresponding constructor arugments could be optional and default to values provided via the config file (Elasticluster for example creates a default `gc3` account for SLURM, which could be already provided in the config file template).

**Comment by riccardomurri** [comment]
> There are cases where one needs to provide additional submission
> arguments. For example, to implement fair job scheduling across
> multiple users and accounts with SLURM one may need to specify
> --account or --user.

This is already supported, just not in the way you suggest.

You need to define a custom application subclass and override the
`sbatch` method (other methods are there for other batch-queing
systems)::

        class MySlurmApp(Application):
          # ...
          def sbatch(self, resource, **kwargs):
            # get original `sbatch` invocation
            sbatch, cmdline = super(self, Application).sbatch(resource, **kwargs)
            # now you can manipulate the `sbatch invocation
            sbatch = sbatch[:1] + ['--user', self.slurm_user] + sbatch[1:]
            return (sbatch, cmdline)

Keep in mind, however, that this will make your code batch-system
specific, i.e., it may not run correctly with e.g. a GridEngine
backend.

**Comment by HackerMD** [comment]
Sweet! I like!
