### ISSUE TITLE
SSL error: decryption failed or bad record mac

### ISSUE THREAD

**Issue by riccardomurri** [uzh/gc3pie#550]
_(Originally posted by @HackerMD in #546)_

I repeatedly get this error when running the engine on a uWSGI server with multiple processes:

```
  File "/home/ubuntu/gc3pie_code/gc3libs/persistence/sql.py", line 257, in load
    r = conn.execute(q)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (psycopg2.DatabaseError) SSL error: decryption failed or bad record mac
 [SQL: 'SELECT tasks.data \nFROM tasks \nWHERE tasks.id = %(id_1)s'] [parameters: {'id_1': 213068}]
```

The sql statement is fine and the row exists:

```
select tasks.data from tasks where tasks.id = 213068;
```

The sqlalchemy docs give a hint:

> For a multiple-process application that uses the os.fork system
> call, or for example the Python multiprocessing module, it’s usually
> required that a separate Engine be used for each child process. This
> is because the Engine maintains a reference to a connection pool
> that ultimately references DBAPI connections - these tend to not be
> portable across process boundaries. An Engine that is configured not
> to use pooling (which is achieved via the usage of NullPool) does
> not have this requirement.

Indeed, when I run uWSGI with lazy-apps option, I don't get this error. I cannot use this option for other reasons, however.

**Comment by riccardomurri** [comment]
*(Again re-posting a comment by @HackerMD)*

I hacked the SqlStore such that the engine doesn't get created in the constructor upon creation of the store object, but lazily when the _engine attribute is first getting accessed (using a property whose return value gets cached):

```
def __init__(self, url, table_name="store", idfactory=None,
                 extra_fields={}, create=True, **extra_args):
        """
        Open a connection to the storage database identified by
        url. It will use the correct backend (MySQL, psql, sqlite3)
        based on the url.scheme value
        """
        super(SqlStore, self).__init__(url)
        self.__engine = None
        self._t_store = None
        self._extra_fields = extra_fields
        self._create = create
        self.table_name = table_name

        self.idfactory = idfactory
        if not idfactory:
            self.idfactory = IdFactory(id_class=IntId)

    @property
    def _engine(self):
        if self.__engine is None:
            self.__engine = sqla.create_engine(str(self.url))
        return self.__engine

    @property
    def t_store(self):
        if self._t_store is None:
            self.__meta = sqla.MetaData(bind=self._engine)
            # create schema
            table = sqla.Table(
                self.table_name,
                self.__meta,
                sqla.Column('id',
                            sqla.Integer(),
                            primary_key=True, nullable=False),
                sqla.Column('data',
                            sqla.LargeBinary()),
                sqla.Column('state',
                            sqla.String(length=128)))

            # create internal rep of table
            self.extra_fields = dict()
            for col, func in self._extra_fields.iteritems():
                assert isinstance(col, sqla.Column)
                table.append_column(col.copy())
                self.extra_fields[col.name] = func

            current_metadata = sqla.MetaData(bind=self._engine)
            current_metadata.reflect()

            # check if the db exists and already has a 'store' table
            if self._create and self.table_name not in current_metadata.tables:
                self.__meta.create_all()

            self._t_store = self.__meta.tables[self.table_name]
        return self._t_store
```

This fixed the SSL error.

Funnily I got another error as predicted, when another process tried to select the row based on the returned persistent_id before it got actually inserted into the table:

      File "/home/ubuntu/gc3pie_code/gc3libs/persistence/sql.py", line 273, in load
        "Unable to find any object with ID '%s'" % id_)
    gc3libs.exceptions.LoadError: Unable to find any object with ID 'None'

**Comment by riccardomurri** [comment]
> This fixed the SSL error.

If your diagnosis of the problem being related to uWSGI executing the same code in multiple processes is correct, what is probably happening is the following: since creation of the SqlAlchemy Engine is delayed until the first actual use, each process gets its own SqlAlchemy Engine instance.

Still, it's not clear to me how and why the initialization code would be executed *before* the fork, and the request-specific code *after*.


> I got another error as predicted, when another process tried to
> select the row based on the returned persistent_id before it got
> actually inserted into the table:
> ```
>   File "/home/ubuntu/gc3pie_code/gc3libs/persistence/sql.py", line 273, in load
>     "Unable to find any object with ID '%s'" % id_)
> gc3libs.exceptions.LoadError: Unable to find any object with ID 'None'
> ```

However the error message complains that the object ID has not been assigned (``None``) rather than assigned but not yet saved ...

**Comment by HackerMD** [comment]
> Still, it's not clear to me how and why the initialization code would be executed before the fork, and the request-specific code after.

GC3Pie is used as a flask extension. The app and its extensions get created before uWSGI forks the application.

**Comment by riccardomurri** [comment]
Code fixing this (contributed by @HackerMD ) has been merged in the "feature/tissuemaps" branch and will be soon merged into "master".
