### ISSUE TITLE
Support Keystone V3 API

### ISSUE THREAD

**Issue by arcimboldo** [uzh/gc3pie#557]
If OpenStack is configured with multiple domains (https://wiki.openstack.org/wiki/Domains) and you want to use an user which is not member of the "default" domain, you _need_ to use V3 authentication when interacting with Keystone.

GC3Pie doesn't currently support Keystone V3, but we should support it.

**Comment by riccardomurri** [comment]
This was fixed in https://github.com/gc3-uzh-ch/elasticluster/commit/50a958db667063c719a5a3761ea6cb19e4d239af#diff-5598dd39d17ffcef0702e7afffa390c7 and subsequent commits.
