### ISSUE TITLE
Misleading error message about resource limits

### ISSUE THREAD

**Issue by riccardomurri** [uzh/gc3pie#575]
When task submission fails in the `shellcmd` backend because of a resource
limit, a message is printed stating the problem and offering a suggestion to
fix::

```
DEBUG   : Ignoring error in submitting to resource '...': Resource ... already running maximum allowed number of jobs (1). Increase 'max_cores' to raise.
```

However, when `override=yes` (soon to become: `discover=yes`) the suggestion
"Increase 'max_cores' to raise." is incorrect and misleading: (1) changing the
configuration file will be ineffective, and (2) there might be no configuration
file to change (as is the case for cloud-based resources).

GC3Pie should omit the "Increase 'max_cores'" suggestion when override/discover is true.

**Comment by HackerMD** [comment]
I am constantly getting this message on `shellcmd` backend with `override=no` when using an engine with `max_in_flight` and/or `max_submitted` greater than `max_cores`:

```
ERROR: Got error in submitting task '76390', informing scheduler: LRMSSubmitError: Resource localhost already running maximum allowed number of jobs (4). Increase 'max_cores' to raise.
```

This should not be an `ERROR` message, but rather a `DEBUG` message (if a message is required at all). Ideally, the engine wouldn't even make an attempt to submit additional tasks in the first place.
