### ISSUE TITLE
Path to jobdir ($HOME/.gc3pie_jobs) should be configurable

### ISSUE THREAD

**Issue by akesandgren** [uzh/gc3pie#576]
The path and name of jobdir ($HOME/.gc3pie_jobs) should be configurable.

There are sites which have a non-writable $HOME file system from the batch nodes/jobs.

Preferably the config should be able to handle a global setting that can expand env variables at runtime.
I.e., a global setting of jobdir=/pfs/nobackup$HOME/.gc3pie_jobs which then expands per user at runtime.

Or something similar.

**Comment by riccardomurri** [comment]
Fixed in commit 3a72fa0c33290a291a67c2613eb6396203f05333 -- configuration item `spooldir` can now be used to set that path.
