### ISSUE TITLE
SessionClient' object has no attribute 'auth_token'"

### ISSUE THREAD

**Issue by smaffiol** [uzh/gc3pie#605]
when running an ordinary gc3pie script on an ubuntu 16.04.1

AttributeError: "'SessionClient' object has no attribute 'auth_token'"
> /home/ubuntu/gc3pie/src/gc3libs/backends/openstack.py(218)_connect()
-> if not self.client.client.auth_token or not self._flavors:

p novaclient.__version__
'7.1.0'

S.

**Comment by riccardomurri** [comment]
Should be fixed in commit https://github.com/uzh/gc3pie/commit/2b74317a48db245c6c790a7d0fe646848ecd739f -- can you please test?

**Comment by riccardomurri** [comment]
From private conversation: the fix works, but who knows how backwards compatible it is ...
