### ISSUE TITLE
Shellcmd backend does not report execution stats in 2.4.2

### ISSUE THREAD

**Issue by ehrenfeu** [uzh/gc3pie#619]
As stated in the title, in release 2.4.2 the `shellcmd` backend doesn't report execution stats after a job has finished (e.g. used memory, duration, CPU time, ...).

Am I correct in assuming this has been fixed in 1fc0952ce6d48679684f80a54a3ddc31f89e4b7c ?

Thanks,
Niko

**Comment by riccardomurri** [comment]
Yes, the fix is already in the "master" branch.
