### ISSUE TITLE
Shellcmd overrides transport settings. Result: connection to frontend with user 'None' 

### ISSUE THREAD

**Issue by smaffiol** [uzh/gc3pie#621]
in gc3libs/backends/shellcmd.py:

        def fset(self, value):
            self._frontend = value
            self.transport.set_connection_params(value)

this method gets called, for example at line: 343
        self.frontend = frontend

right after self.transport has been initialisated with an instance of gc3libs.backends.transport.SshTranspor
were all the relevant connection parameters - e.g. username - have been passed.

because of the 'fset' the call self.frontend = frontend triggers another call of self.transport.set_connection_params(value) were the default settings are set again on the transport object resulting, for example, in a reset of the username.

Proposed change:
        def fset(self, value):
            self._frontend = value
            # self.transport.set_connection_params(value)

- better: remove the set_connectio_params(value) line

S.

**Comment by riccardomurri** [comment]
Fixed in commit 02e3afe
