### ISSUE TITLE
AttributeError: 'ShellcmdLrms' object has no attribute '_make_remote_and_local_path_pair'

### ISSUE THREAD

**Issue by riccardomurri** [uzh/gc3pie#627]
Reported by @ehrenfeu in #458:

> In the meantime I did some more debugging and found out the problem only occurs with jobs that have the `outputs` parameter set to non-empty. Increasing the loglevel to maximum results in the following messages:
> ```
> gc3.gc3libs: DEBUG: About to update state of application: HuDeconApp@7fb684473550 (currently: SUBMITTED)
> gc3.gc3libs: DEBUG: Executed local command 'ps -p 25531 -o state=', got exit status: 1
> gc3.gc3libs: DEBUG: Process with PID 25531 not found, assuming task HuDeconApp@7fb684473550 has finished running.
> gc3.gc3libs: DEBUG: Calling state-transition handler 'terminating' on HuDeconApp@7fb684473550 ...
> gc3.gc3libs: DEBUG: Updating job info file for pid 25531
> gc3.gc3libs: DEBUG: Reading resource utilization from wrapper file `/data/snijder_spooldir/gc3libs.XEGCfR/.gc3pie_shellcmd/resource_usage.txt` for task HuDeconApp@7fb684473550 ...
> gc3.gc3libs: DEBUG: Deleting job info file for pid 25531 ...
> gc3.gc3libs: DEBUG: Removing /data/gc3_resourcedir/shellcmd.d/25531
> gc3.gc3libs: DEBUG: Recovered resource information from files in /data/gc3_resourcedir/shellcmd.d: total nr. of cores: 2, requested by jobs: 0; available memory: 2000MB, requested by jobs: 0MB.
> gc3.gc3libs: DEBUG: Ignored error in fetching output of task 'HuDeconApp@7fb684473550': AttributeError: 'ShellcmdLrms' object has no attribute '_make_remote_and_local_path_pair'
> gc3.gc3libs: DEBUG: (Original traceback follows.)
> Traceback (most recent call last):
>   File "/home/ehrenfeu/gc3pie/src/gc3libs/core.py", line 1805, in progress
>     changed_only=self.retrieve_changed_only)
>   File "/home/ehrenfeu/gc3pie/src/gc3libs/core.py", line 607, in fetch_output
>     app, download_dir, overwrite, changed_only, **extra_args)
>   File "/home/ehrenfeu/gc3pie/src/gc3libs/core.py", line 675, in __fetch_output_application
>     raise ex
> AttributeError: 'ShellcmdLrms' object has no attribute '_make_remote_and_local_path_pair'
> ```

**Comment by riccardomurri** [comment]
@ehrenfeu can you please test this and confirm it fixes your issue with managed jobs?

**Comment by ehrenfeu** [comment]
Thanks, @riccardomurri - I didn't have much time yet but I ran a few of those tests that were recently failing and it looks quite good!!
I'll do some more testing in the next few days to make sure everything behaves now as expected, but currently I'd say this looks as if everything is working - actually, for the first time, yay!

:smiley:

Thanks again, I'll report more in the next days!
