### ISSUE TITLE
BUG: ShellCmd remove self.job_infos break openstack, ec2 and gsession

### ISSUE THREAD

**Issue by smaffiol** [uzh/gc3pie#628]
ShellCmd.job_infos is used by openstack and ec2 backends as well as by commands to determine the number of running jobs on a given instance - note, this is specific to cloud type of resources.

During commit 7ff59bca57023ef9894b80cd7d5dccde4ddfcbc3
ShellCmd.job_infos has been removed in favor of ShellCmd._job_infos and various utility methods.
As Riccardo suggested, a new method like: 'has_jobs' or 'running_jobs' should be added to report the number of currently running jobs

possible example:
def running_jobs(self):
    return len(self._get_persisted_job_info())

or simply
def running_jobs(self):
    return len(self._job_infos)

as such checks are always called after invoking ShellCmd.get_resource_status()

S.

**Comment by riccardomurri** [comment]
Fixed in commit 0c4ba9b
